services:
  gateway:
    image: nginx:1.28-alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
