## docs: https://docs.docker.com/reference/compose-file/

services:
  gateway:
    image: nginx:1.28-alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - '9000:9000' # Web console & API
      - '9001:9001' # Admin console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
    command: server /data --console-address ":9001"

volumes:
  rabbitmq_data:
  minio_data:
