## docs: https://docs.docker.com/reference/compose-file/

services:
  gateway:
    image: nginx:1.28-alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001' # Admin console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001" # Launches admin console

volumes:
  rabbitmq_data:
  postgres_data:
  minio_data:
