services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  gateway:
    image: nginx:1.28-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf

  courses:
    build: ./services/courses
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./services/courses:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # To use tsx watch mode on docker

  media:
    build: ./services/media
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./services/media:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # To use tsx watch mode on docker
