services:
  gateway:
    image: nginx:1.28-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    build: ./frontend
    restart: unless-stopped
    expose:
      - "5173"
    volumes:
      - ./frontend:/app

  courses:
    build: ./services/courses
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./services/courses:/app

  media:
    build: ./services/media
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./services/media:/app
